### ISSUE TITLE
street address vs. email address

### ISSUE THREAD

**Issue by clararaubertas** [Parallactic/callgov#14]
currently it 500s if you enter an email instead of a street address. it should both fail gracefully for that, and make it more clear that it's asking for street address

**Comment by faraocious** [comment]
should we just make the prompt for the "address" box "Enter your mailing address"?

we can also handle the exception, but that might set people on the right path off the block.

**Comment by clararaubertas** [comment]
it now specifies "street address"; handling the exception coming soon :)
